set dotenv-load
set positional-arguments

run *ARGS:
    echo 'drop extension if exists sid; create extension sid;' | cargo pgx run
    cargo pgx connect

test *ARGS:
    cargo test
    # cargo pgx test

build:
    cargo build

install:
    cargo pgx install

check:
    cargo check

release:
    cargo pgx package